name: mapbox_gl_web
publish_to: 'none'
version: 0.16.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  mapbox_gl_platform_interface: ^0.16.0
  js: ^0.7.2

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: src/mapbox_web_gl.dart
